
services:
  web:
    build: ./web
    ports:
      - "8080:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=app_db
    depends_on:
       - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - app-network

  db:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 